name: Test sim

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    run-tests:
        name: "Run tests"
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2

            - name: Set up Node.js
              uses: actions/setup-node@v4.4.0
              with:
                  node-version: "lts/jod"

            - name: Install dependencies
              working-directory: sim
              run: npm ci

            - name: Run tests
              working-directory: sim
              run: npm run test
